# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"MyServer": "01_to_csv.ipynb",
         "Handel": "01_to_csv.ipynb",
         "datetime_fix": "01_to_csv.ipynb",
         "get_activities": "01_to_csv.ipynb",
         "Handel.get_activities": "01_to_csv.ipynb",
         "get_streams": "01_to_csv.ipynb",
         "parse_activity": "01_to_csv.ipynb",
         "parse_activitys": "01_to_csv.ipynb",
         "Handel.get_streams": "01_to_csv.ipynb",
         "Handel.parse_activity": "01_to_csv.ipynb",
         "Handel.parse_activitys": "01_to_csv.ipynb",
         "interpolate": "02_parse.ipynb",
         "moving_average": "02_parse.ipynb",
         "training_impulse": "02_parse.ipynb",
         "Zones": "02_parse.ipynb",
         "training_impulse_hr": "02_parse.ipynb",
         "parse_tss": "02_parse.ipynb"}

modules = ["to_csv.py",
           "parse.py"]

doc_url = "https://takotabak.github.io/strava_overview/"

git_url = "https://github.com/takotabak/strava_overview/tree/master/"

def custom_doc_links(name): return None
