# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"upload_file": "00_s3.ipynb",
         "download_file": "00_s3.ipynb",
         "EmailIndex": "01_models.ipynb",
         "AlreadyFoundExeption": "01_models.ipynb",
         "IncorrectPassword": "01_models.ipynb",
         "LockedAccount": "01_models.ipynb",
         "Athlete": "01_models.ipynb",
         "types": "01_models.ipynb",
         "Handel": "01_models.ipynb",
         "dagen_van_week": "01_models.ipynb",
         "Activity": "01_models.ipynb",
         "datetime_fix": "01_models.ipynb",
         "get_activities": "01_models.ipynb",
         "Handel.get_activities": "01_models.ipynb",
         "emoji_name": "01_models.ipynb",
         "emoji_dct": "01_models.ipynb",
         "save_activities": "01_models.ipynb",
         "Handel.save_activities": "01_models.ipynb",
         "interpolate": "02_ti.ipynb",
         "moving_average": "02_ti.ipynb",
         "norm_power": "02_ti.ipynb",
         "training_impulse_power": "02_ti.ipynb",
         "Zones": "02_ti.ipynb",
         "training_impulse_hr": "02_ti.ipynb",
         "get_ftp": "02_ti.ipynb",
         "Activity.get_ftp": "02_ti.ipynb",
         "get_max_heartrate": "02_ti.ipynb",
         "Activity.get_max_heartrate": "02_ti.ipynb",
         "make_ti": "02_ti.ipynb",
         "Activity.make_ti": "02_ti.ipynb",
         "characters": "04_auth.ipynb",
         "Tokens": "04_auth.ipynb",
         "tokens": "04_auth.ipynb",
         "go_strava_auth": "04_auth.ipynb",
         "save_code_to_token": "05_backend.ipynb"}

modules = ["s3.py",
           "models.py",
           "ti.py",
           "auth.py",
           "backend.py",
           "plots.py"]

doc_url = "https://takotabak.github.io/strava_overview/"

git_url = "https://github.com/takotabak/strava_overview/tree/master/"

def custom_doc_links(name): return None
