# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_backend.ipynb (unless otherwise specified).

__all__ = ['save_code_to_token']

# Cell
from .imports import *
from .s3 import *
from .auth import *
from .models import *


# Cell
def save_code_to_token(state, tokens=None, client = None, make_ath=True):
    """Excecuted by the backend if a new code is coming in."""
    client = ifnone(client, stravalib.client.Client())
    tokens = ifnone(tokens, Tokens())
    token = client.exchange_code_for_token(
            client_id=client_id, client_secret=secret, code=state["code"],
        )
    client.access_token = token['access_token']
    athlete = client.get_athlete()

    if make_ath:
        ath = Athlete.from_stravalib(athlete)
        ath.access_token = token['access_token']
        ath.refresh_token = token['refresh_token']
        ath.save()

    _, tok = tokens.add(athlete.id)
    return tok

