# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/Untitled.ipynb (unless otherwise specified).

__all__ = ['parse_tss']

# Cell
from .to_csv import *

# Cell
def parse_tss(df, threshold = 179, ftp = 339):
    df.index = df['time']
    df.reindex(np.arange(df.index[-1]))
    if 'watts' in list(df.columns):
        df['ftp'] = df['watts']
        print('watts')
    elif 'heartrate' in list(df.columns):
        df['ftp'] = (df['heartrate'])/ (threshold)
    else:
        print(df.columns)
    return df
