# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_s3.ipynb (unless otherwise specified).

__all__ = ['upload_file', 'download_file']

# Cell
import json
import os
from typing import Dict

from fastcore.all import *
import boto3
from dotenv import load_dotenv, find_dotenv
load_dotenv(find_dotenv())

# Cell
def upload_file(f, upload_file=None) -> bool:
    upload_file = ifnone(upload_file, f)
    _id,secret = os.getenv("AWS_ACCESS_KEY_ID"), os.getenv("AWS_SECRET_ACCESS_KEY")
    s3_client = boto3.client("s3",
        aws_access_key_id=_id,
        aws_secret_access_key=secret,
                            )
    r = s3_client.upload_file(f, "motionreview", upload_file)
    return True

# Cell
def download_file(filename):
    s3 = boto3.client('s3')
    with open(filename, 'wb') as f:
        s3.download_fileobj('motionreview', filename, f)