name: Deploy master
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Generate deployment package
      #   run: deploy.sh

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v5
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: motionreview
          environment_name: Motionreview-env
          version_label: 1
          region: eu-central-1
          deployment_package: deploy.zip
